name: jupyterhub
channels:
  - conda-forge
  - nodefaults
dependencies:
  - altair
  - bokeh
  - datashader
  - hvplot
  - notebook
  - numba
  - numpy
  - pandas
  - panel
  - param
  - plotly
  - pydeck
  - python=3.9
  - pyvista
  - scikit-learn
  - scipy
  - seaborn
  - xarray
  - xgboost
