name: jupyterhub
channels:
  - conda-forge
  - nodefaults
dependencies:
  - altair
  - numba
  - pandas
  - notebook
  - hvplot
  - numpy
  - param
  - bokeh
  - pyvista
  - scipy
  - xarray
  - datashader
  - scikit-learn
  - xgboost
  - plotly
  - pydeck
  - seaborn
  - pip

